export const constantRoute = [
    {
        path:'/login',
        component:()=>import('../views/login/index.vue'),
        name:'login',
        meta:{
            title:'登录',
            hidden:true
        }
    },
    {
        path:'/',
        component:()=>import('../layout/index.vue'),
        name:'layout',
        meta:{
            title:'登录',
            hidden:true
        }
    },
    {
        path:'/404',
        component:()=>import('../views/404/index.vue'),
        name:'404',
        meta:{
            title:'登录',
            hidden:true
        }
    },
    {
        path:'/:pathMatch(.*)*',
        redirect:'/404',
        name:'Any',
        meta:{
            title:'登录',
            hidden:true
        }
    },
    {
        path:'/home',
        name:'home',
        component:()=>import('../layout/index.vue'),
        meta:{
            title:'我的应用',
            hidden:false,
            icon:'Lock'
        },
        children:[
                {
                    path:'/app/dev',
                    component:()=>import('../views/home/my_dev_app/index.vue'),
                    name:'dev_app',
                    meta:{
                        title:'我开发的应用',
                        hidden:false,
                        icon:'User'
                    }
                },
                {
                    path:'/app/get',
                    component:()=>import('../views/home/my_get_app/index.vue'),
                    name:'get_app',
                    meta:{
                        title:'我获取的应用',
                        hidden:false,
                        icon:'Monitor'
                    }
                },
                {
                    path:'/app/edit',
                    component:()=>import('../views/home/edit_content/index.vue'),
                    name:'edit',
                    meta:{
                        hidden:true
                    }
                }
        ]
    },
]